name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_email: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          export_default_credentials: true

      - name: Build Docker Image
        run: |
          
          docker build -t us-central1-docker.pkg.dev/end-to-end-project-438607/node-apps/hello-world-app1:latest .

      - name: Push Docker Image to Artifact Registry
        run: |
          # Push the Docker image to Google Cloud Artifact Registry
          docker push us-central1-docker.pkg.dev/end-to-end-project-438607/node-apps/hello-world-app1:latest
